# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Create a new Beta Build"
  lane :build do
    gym(
      scheme: "controlhub",
      clean: true,
      xcargs: "CODE_SIGN_IDENTITY='' CODE_SIGNING_REQUIRED='NO' CODE_SIGN_ENTITLEMENTS='' CODE_SIGNING_ALLOWED='NO'"
    )
  
  end

  desc "Create a new Beta Build and deploy to firebase"
  lane :deplsdfsdfoy do
    
    # xcodebuild(
    #   scheme: "servicehayah",
    #   xcargs: "CODE_SIGN_IDENTITY='' CODE_SIGNING_REQUIRED='NO' CODE_SIGN_ENTITLEMENTS='' CODE_SIGNING_ALLOWED='NO'"
    # )
    
    gym(
      scheme: "servicehayah",
      clean: true,
      xcargs: "CODE_SIGN_IDENTITY='' CODE_SIGNING_REQUIRED='NO' CODE_SIGN_ENTITLEMENTS='' CODE_SIGNING_ALLOWED='NO'"
    )
    firebase_app_distribution(
      service_credentials_file: ENV["SERVICE_CREDENTIALS_FILE"],
      app: ENV["FIREBASE_APP_ID"],
      groups: "interns",
      release_notes: "Stub",
      debug: true
    )
  end
end
