# This file contains the fastlane.tools configuration for iOS
# Documentation: https://docs.fastlane.tools
# Available Actions: https://docs.fastlane.tools/actions
# Available Plugins: https://docs.fastlane.tools/plugins/available-plugins

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Runs all the tests"
  lane :test do
    scan # runs all the tests
  end

  desc "Build the iOS app"
  lane :build do
    match(type: "appstore") # Fetch certificates and provisioning profiles
    gym(scheme: "MannyDesigns") # Build your app
  end

  desc "Submit a new Beta Build to Firebase App Distribution"
  lane :beta do
    match(type: "appstore") # Fetch certificates and provisioning profiles
    gym(scheme: "MannyDesigns") # Build your app

    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID_IOS"],
      groups: "testers",
      release_notes: "Beta release notes",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"]
    )
  end

  desc "Deploy a new version to the App Store"
  lane :deploy do
    match(type: "appstore") # Fetch certificates and provisioning profiles
    gym(scheme: "MannyDesigns") # Build your app
    deliver(force: true) # Upload to App Store
  end
end
